kind = "mobile"
previewPath = "/mobile/"
title = "Livia Mobile"
version = "1.0.0"
id = "artifacts/bliq-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24839

[services.development]
run = "pnpm --filter @workspace/bliq-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bliq-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/bliq-mobile", "run", "serve" ]

[services.env]
PORT = "24839"
BASE_PATH = "/mobile/"
