import { getMonitoringOverview } from "./internal-monitoring.service";
import { listVerticalCoverage } from "@workspace/policy";
import { searchInternalTenants } from "./internal-ops.service";

export async function buildWeeklyPlatformReport(): Promise<{
  generatedAt: string;
  markdown: string;
  stats: Record<string, number | string>;
}> {
  const generatedAt = new Date().toISOString();
  const overview = await getMonitoringOverview();
  const tenants = await searchInternalTenants({ limit: 1, offset: 0 });
  const verticals = listVerticalCoverage();
  const betaFull = verticals.filter((v) => v.tier === "beta-full" || v.tier === "heartland").length;

  const md = [
    `# Livia platform weekly — ${generatedAt.slice(0, 10)}`,
    "",
    "## Health",
    `- Open alert firings: **${overview.alerts.openCount}**`,
    `- Bookings / minute (last hour): **${overview.live.bookingsPerMinuteLastHour}**`,
    `- Events (15m): **${overview.live.eventsLast15m}**`,
    `- Failed notifications (15m): **${overview.live.failedNotificationsLast15m}**`,
    "",
    "## Tenants",
    `- Total businesses indexed: **${tenants.total}**`,
    "",
    "## Vertical coverage",
    `- Registry entries: **${verticals.length}**`,
    `- Beta-full + heartland: **${betaFull}**`,
    "",
    "## Actions",
    "1. Triage open alert firings in Monitoring.",
    "2. Review support queue SLA.",
    "3. Confirm demo world provisioned for sales demos.",
    "",
    "_Generated by internal ops — not customer-facing._",
  ].join("\n");

  return {
    generatedAt,
    markdown: md,
    stats: {
      openAlerts: overview.alerts.openCount,
      tenantTotal: tenants.total,
      verticalRegistry: verticals.length,
    },
  };
}
