uploads = []
outputs = []

[[generated]]
id = "ZaCqvP5QzimB-lZWdbKYH"
uri = "file://artifacts/livia-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5gCYo1rTMJGXUFs0sS_0V"
uri = "file://artifacts/livia-marketing/public/og.png"
type = "image"
title = "OG Image Livia"

[[generated]]
id = "NIUuw6R06Z-o6AE_7VSrD"
uri = "file://artifacts/livia-marketing/public/product-surface.png"
type = "image"
title = "Software Surface Abstract"

[[generated]]
id = "MeeDet8E2Qp1sFlPSzf7j"
uri = "file://artifacts/livia-marketing/public/aurora-abstract.png"
type = "image"
title = "Aurora abstract composition"
