/**
 * Isolated demo logins — one real-world scenario per account (no 17-shop founder soup).
 * Provisioned alongside DEMO_PERSONAS in demo-portal.service.
 */
import { DEMO_ROLE_EMAILS } from "@workspace/demo-logins";
import type { DemoPersonaDef } from "./demo-portal-config";

export const DEMO_SCENARIO_ACCOUNTS: DemoPersonaDef[] = [
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.solo,
    displayName: "Conor McGee",
    roleLabel: "Solo barber · Stoneybatter",
    firstName: "Conor",
    lastName: "McGee",
    landingPath: "/dashboard",
    primaryBusinessSlug: "stoneybatter-cuts",
    businessSlugs: ["stoneybatter-cuts"],
    requiresClerk: true,
  },
  {
    id: "manager",
    email: DEMO_ROLE_EMAILS.studioBarber,
    displayName: "Roisin Doherty",
    roleLabel: "Studio barber · six-chair",
    firstName: "Roisin",
    lastName: "Doherty",
    landingPath: "/inbox",
    membershipRole: "ADMIN",
    primaryBusinessSlug: "dublin-barber-collective",
    businessSlugs: ["dublin-barber-collective"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.soloWellness,
    displayName: "Maeve Collins",
    roleLabel: "Solo wellness · Dundrum House",
    firstName: "Maeve",
    lastName: "Collins",
    landingPath: "/dashboard",
    primaryBusinessSlug: "dundrum-serenity-spa",
    businessSlugs: ["dundrum-serenity-spa"],
    requiresClerk: true,
  },
  {
    id: "org_admin",
    email: DEMO_ROLE_EMAILS.chain,
    displayName: "Aoife O'Connor",
    roleLabel: "Org admin · Aurora chain",
    firstName: "Aoife",
    lastName: "O'Connor",
    landingPath: "/chain",
    primaryBusinessSlug: "aurora-studio",
    businessSlugs: ["aurora-studio", "aurora-mews", "aurora-galway"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.uk,
    displayName: "Amelia Hart",
    roleLabel: "Owner · London (GB)",
    firstName: "Amelia",
    lastName: "Hart",
    landingPath: "/dashboard",
    primaryBusinessSlug: "london-rose-spa",
    businessSlugs: ["london-rose-spa"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.de,
    displayName: "Jonas Weber",
    roleLabel: "Owner · Berlin (DE)",
    firstName: "Jonas",
    lastName: "Weber",
    landingPath: "/dashboard",
    primaryBusinessSlug: "berlin-studio-neun",
    businessSlugs: ["berlin-studio-neun"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.medspa,
    displayName: "Dr Ní Cheallaigh",
    roleLabel: "Owner · Medspa",
    firstName: "Clinical",
    lastName: "Lead",
    landingPath: "/dashboard",
    primaryBusinessSlug: "clarity-medspa-dublin",
    businessSlugs: ["clarity-medspa-dublin"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.pets,
    displayName: "Jade Murphy",
    roleLabel: "Owner · Pet grooming",
    firstName: "Jade",
    lastName: "Murphy",
    landingPath: "/dashboard",
    primaryBusinessSlug: "paws-parlour-dublin",
    businessSlugs: ["paws-parlour-dublin"],
    requiresClerk: true,
  },
  {
    id: "owner",
    email: DEMO_ROLE_EMAILS.physio,
    displayName: "Eoin Barrett",
    roleLabel: "Owner · Physio",
    firstName: "Eoin",
    lastName: "Barrett",
    landingPath: "/dashboard",
    primaryBusinessSlug: "motion-physio-cork",
    businessSlugs: ["motion-physio-cork"],
    requiresClerk: true,
  },
];
