import { Router, type IRouter } from "express";
import meRouter from "./me";
import businessesRouter from "./businesses";
import staffRouter from "./staff";
import servicesRouter from "./services";
import customersRouter from "./customers";
import bookingsRouter from "./bookings";
import availabilityRouter from "./availability";
import slotsRouter from "./slots";
import dashboardRouter from "./dashboard";
import featureFlagsRouter from "./feature-flags";
import publicRouter from "./public";
import guestHubRouter from "./guest-hub";
import devRouter from "./dev";
import chatRouter from "./chat";
import conversationsRouter from "./conversations";
import marketingRouter from "./marketing";
import communicationsRouter from "./communications";
import smsWebhookRouter from "./sms-webhook";
import voiceWebhookRouter from "./voice-webhook";
import internalCronRouter from "./internal-cron";
import internalOpsRouter from "./internal-ops";
import myDayRouter from "./my-day";
import invitationsRouter from "./invitations";
import onboardingRouter from "./onboarding";
import supportRouter from "./support";
import billingRouter from "./billing";
import billingAddonsRouter from "./billing-addons";
import paymentsRouter from "./payments";
import voiceRouter from "./voice";
import workflowsRouter from "./workflows";
import timeOffRouter from "./time-off";
import auditLogRouter from "./audit-log";
import peerInsightsRouter from "./peer-insights";
import partnerApiRouter from "./partner-api";
import integrationsRouter from "./integrations";
import experienceRouter from "./experience";
import demoRouter from "./demo";
import launchRouter from "./launch";
import lifecycleRouter from "./lifecycle";
import livRouter from "./liv";
import chairRentalRouter from "./chair-rental";
import payrollRouter from "./payroll";
import staffShiftsRouter from "./staff-shifts";
import shiftTemplatesRouter from "./shift-templates";
import importRouter from "./import";
import integrationBrokersRouter from "./integration-brokers";
import classSessionsRouter from "./class-sessions";
import packageCreditsRouter from "./package-credits";
import designProofsRouter from "./design-proofs";
import medspaRouter from "./medspa";
import enterpriseRouter from "./enterprise";
import premisesRouter from "./premises";
import bookingResourcesRouter from "./booking-resources";
import dayPackagesRouter from "./day-packages";
import careSeriesRouter from "./care-series";
import franchisePolicyRouter from "./franchise";
import wellnessRouter from "./wellness";
import beautyRouter from "./beauty";
import hairRouter from "./hair";
import alliedHealthRouter from "./allied-health";
import consultFirstRouter from "./consult-first";

const router: IRouter = Router();

router.use(meRouter);
router.use(onboardingRouter);
router.use(businessesRouter);
router.use(supportRouter);
router.use(staffRouter);
router.use(servicesRouter);
router.use(customersRouter);
router.use(bookingsRouter);
router.use(availabilityRouter);
router.use(slotsRouter);
router.use(dashboardRouter);
router.use(featureFlagsRouter);
router.use(publicRouter);
router.use(guestHubRouter);
router.use(chatRouter);
router.use(conversationsRouter);
router.use(marketingRouter);
router.use(communicationsRouter);
router.use(smsWebhookRouter);
router.use(voiceWebhookRouter);
router.use(internalCronRouter);
router.use(internalOpsRouter);
router.use(myDayRouter);
router.use(invitationsRouter);
router.use(billingRouter);
router.use(billingAddonsRouter);
router.use(paymentsRouter);
router.use(voiceRouter);
router.use(workflowsRouter);
router.use(timeOffRouter);
router.use(auditLogRouter);
router.use(peerInsightsRouter);
router.use(integrationsRouter);
router.use(experienceRouter);
router.use(demoRouter);
router.use(launchRouter);
router.use(lifecycleRouter);
router.use(livRouter);
router.use(chairRentalRouter);
router.use(payrollRouter);
router.use(staffShiftsRouter);
router.use(shiftTemplatesRouter);
router.use(importRouter);
router.use(integrationBrokersRouter);
router.use(classSessionsRouter);
router.use(packageCreditsRouter);
router.use(designProofsRouter);
router.use(medspaRouter);
router.use(enterpriseRouter);
router.use(premisesRouter);
router.use(bookingResourcesRouter);
router.use(dayPackagesRouter);
router.use(careSeriesRouter);
router.use(franchisePolicyRouter);
router.use(wellnessRouter);
router.use(beautyRouter);
router.use(hairRouter);
router.use(alliedHealthRouter);
router.use(consultFirstRouter);
router.use(partnerApiRouter);
router.use(devRouter);

export default router;
