/**
 * Extended incumbent catalog — tier 2/3 platforms across all verticals.
 * Merged into INCUMBENT_MIGRATION_SOURCES in incumbent-migration-atlas.ts.
 */
import type { BusinessVertical } from "./types";
import type {
  MigrationEntityExport,
  MigrationEntityKind,
  IncumbentMigrationSource,
} from "./incumbent-migration-atlas";

const csv = (kind: MigrationEntityKind, steps: string[], notes?: string): MigrationEntityExport => ({
  kind,
  available: true,
  method: "self_serve_csv",
  ownerSteps: steps,
  livPath: "universal_csv",
  notes,
});

const manual = (kind: MigrationEntityKind, steps: string[]): MigrationEntityExport => ({
  kind,
  available: false,
  method: "manual_entry",
  ownerSteps: steps,
  livPath: "manual_entry",
});

export const INCUMBENT_MIGRATION_EXTENDED: IncumbentMigrationSource[] = [
  {
    id: "jane",
    displayName: "Jane App",
    verticals: ["allied-health", "wellness"],
    regions: ["AU", "NZ", "GB", "CA"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 45 },
    parallelRunRecommended: true,
    pickerSubtitle: "Physio & allied health — patient export",
    livIntro: "Jane's patient list exports cleanly. Pull clients and upcoming appointments from Reports — I'll map practitioners to your Livia team.",
    referenceUrls: ["https://jane.app/guide/exporting-data"],
    entities: [
      csv("clients", [
        "Jane → Reports → Patients → export CSV with contact details.",
        "Include email and mobile for Liv guest recognition.",
      ]),
      csv("appointments", [
        "Reports → Appointments → date range covering your cutover window → CSV.",
      ]),
      manual("services", ["Export treatment list from Jane settings or paste your fee schedule CSV."]),
      manual("staff", ["Practitioner names appear in appointment export — add emails under Team in Livia."]),
    ],
  },
  {
    id: "cliniko",
    displayName: "Cliniko",
    verticals: ["allied-health", "wellness"],
    regions: ["AU", "NZ", "GB", "IE"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 15, max: 35 },
    parallelRunRecommended: true,
    pickerSubtitle: "Allied health — patient & appointment CSV",
    livIntro: "Cliniko exports patients and appointments from Reports. Solo practitioners often cut over in one session.",
    referenceUrls: ["https://help.cliniko.com/en/articles/1028753-exporting-data"],
    entities: [
      csv("clients", ["Cliniko → Patients → Export → CSV."]),
      csv("appointments", ["Reports → Appointments → upcoming range → Export CSV."]),
      manual("services", ["Settings → Products & services — export or paste your treatment menu."]),
      manual("staff", ["Practitioner column in appointments — add team emails in Livia."]),
    ],
  },
  {
    id: "zenoti",
    displayName: "Zenoti",
    verticals: ["medspa", "wellness", "hair", "beauty"],
    regions: ["US", "GB", "AU", "IN"],
    tier: "tier2_common",
    livStatus: "partner_required",
    selfServeMinutesEstimate: { min: 30, max: 90 },
    parallelRunRecommended: true,
    pickerSubtitle: "Medspa & multi-location — partner export",
    livIntro: "Zenoti is enterprise-grade — we'll start with client and appointment CSV from Reports, then parallel-run new bookings on Livia.",
    referenceUrls: ["https://help.zenoti.com/"],
    entities: [
      csv("clients", ["Zenoti → Reports → Guest list → CSV export (owner permissions)."]),
      csv("appointments", ["Reports → Appointment details → forward date range → CSV."]),
      manual("services", ["Service catalog export from Zenoti admin or mirror from your booking page."]),
      manual("staff", ["Employee roster from Zenoti HR reports where available."]),
    ],
  },
  {
    id: "mangomint",
    displayName: "Mangomint",
    verticals: ["hair", "beauty", "medspa"],
    regions: ["US", "CA"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 15, max: 35 },
    parallelRunRecommended: false,
    pickerSubtitle: "US salon & spa — client & appointment export",
    livIntro: "Mangomint's exports are straightforward from Reports. Paste clients and upcoming appointments — I'll build your menu from the service list export.",
    entities: [
      csv("clients", ["Mangomint → Reports → Client list → Export CSV."]),
      csv("appointments", ["Reports → Appointments → upcoming → CSV."]),
      csv("services", ["Reports → Service sales or Services list → CSV with duration and price."]),
      manual("staff", ["Add providers under Team — names appear in appointment export."]),
    ],
  },
  {
    id: "glossgenius",
    displayName: "GlossGenius",
    verticals: ["hair", "beauty"],
    regions: ["US"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 15, max: 30 },
    parallelRunRecommended: false,
    pickerSubtitle: "US solo & suite — client CSV",
    livIntro: "GlossGenius lets you export clients. Services mirror from your booking page — share the link and I'll match your menu.",
    entities: [
      csv("clients", ["GlossGenius → Clients → Export client list."]),
      {
        kind: "services",
        available: true,
        method: "public_booking_page",
        ownerSteps: ["Share your GlossGenius booking URL — Liv mirrors your live menu."],
        livPath: "concierge",
      },
      manual("appointments", ["Upcoming appointments from calendar export or screenshot list for concierge setup."]),
      manual("staff", ["Solo default — invite team later if needed."]),
    ],
  },
  {
    id: "setmore",
    displayName: "Setmore",
    verticals: ["wellness", "allied-health", "beauty", "pet-grooming"],
    regions: ["global"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 10, max: 25 },
    parallelRunRecommended: false,
    pickerSubtitle: "Free-tier friendly — customer & appointment export",
    livIntro: "Setmore exports customers and appointments from the app. Good for solo owners switching from a free tier.",
    entities: [
      csv("clients", ["Setmore → Customers → Export."]),
      csv("appointments", ["Setmore → Reports → Appointments → export CSV."]),
      manual("services", ["Services → export list or paste name, duration, price CSV."]),
      manual("staff", ["Staff → export team list where available."]),
    ],
  },
  {
    id: "glofox",
    displayName: "Glofox",
    verticals: ["fitness"],
    regions: ["IE", "GB", "US", "AU"],
    tier: "tier2_common",
    livStatus: "oauth_stub",
    legacyBrokerId: "mindbody",
    selfServeMinutesEstimate: { min: 25, max: 60 },
    parallelRunRecommended: true,
    pickerSubtitle: "Boutique fitness — member export",
    livIntro: "Glofox member and class data needs a careful cutover. Export members and upcoming class bookings first — parallel run recommended for studios.",
    referenceUrls: ["https://support.glofox.com/"],
    entities: [
      csv("clients", ["Glofox → Members → export member list with contact details."]),
      csv("appointments", ["Class schedule / bookings export for forward sessions."]),
      manual("services", ["Class types and pack products — paste from your Glofox price list."]),
      manual("staff", ["Trainer roster from Glofox staff settings."]),
    ],
  },
  {
    id: "honeybook",
    displayName: "HoneyBook",
    verticals: ["event-vendors", "beauty"],
    regions: ["US", "CA"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 45 },
    parallelRunRecommended: false,
    pickerSubtitle: "Event vendors & creatives — project client export",
    livIntro: "HoneyBook is project-centric — export contacts and upcoming booked sessions. Livia handles ongoing appointment booking from your public link.",
    entities: [
      csv("clients", ["HoneyBook → Contacts → Export contacts CSV."]),
      csv("appointments", ["Projects with session dates → export or paste upcoming bookings CSV."]),
      manual("services", ["Service packages from HoneyBook templates — enter as Livia services with duration and deposit rules."]),
      manual("staff", ["Solo or small team — add collaborators under Team."]),
    ],
  },
  {
    id: "gingr",
    displayName: "Gingr",
    verticals: ["pet-grooming"],
    regions: ["US"],
    tier: "tier2_common",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 40 },
    parallelRunRecommended: true,
    pickerSubtitle: "Pet grooming — owner & pet export",
    livIntro: "Gingr exports owners and pets together. Paste the client export — I'll map pets as guest notes until pet profiles ship fully.",
    entities: [
      csv("clients", ["Gingr → Reports → Client list → CSV (includes pet names)."]),
      csv("appointments", ["Reports → Upcoming appointments → CSV."]),
      csv("services", ["Grooming service list from Gingr settings → paste as CSV."]),
      manual("staff", ["Groomer names from appointment export — add under Team."]),
    ],
  },
  {
    id: "petexec",
    displayName: "PetExec",
    verticals: ["pet-grooming"],
    regions: ["US"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 25, max: 50 },
    parallelRunRecommended: true,
    pickerSubtitle: "Pet care & grooming — customer export",
    livIntro: "PetExec customer exports include pet details. Bring forward grooming appointments from Reports for a smooth handoff.",
    entities: [
      csv("clients", ["PetExec → Reports → Customer list → CSV."]),
      csv("appointments", ["Scheduling reports → upcoming grooming appointments → CSV."]),
      manual("services", ["Service catalog from PetExec admin — paste as CSV."]),
      manual("staff", ["Staff list from PetExec settings."]),
    ],
  },
  {
    id: "shopmonkey",
    displayName: "Shopmonkey / detail CRM",
    verticals: ["automotive-detailing"],
    regions: ["US"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 45 },
    parallelRunRecommended: false,
    pickerSubtitle: "Auto detail — customer & job export",
    livIntro: "Export customers and scheduled detail jobs from your shop CRM. Livia treats each job as a booked service with vehicle notes in the appointment.",
    entities: [
      csv("clients", ["CRM → Customers → export CSV with phone and email."]),
      csv("appointments", ["Scheduled jobs / work orders → export upcoming dates CSV."]),
      csv("services", ["Detail packages — paste service name, duration, price CSV."]),
      manual("staff", ["Technician names — add under Team."]),
    ],
  },
  {
    id: "simplybook",
    displayName: "SimplyBook.me",
    verticals: ["wellness", "beauty", "allied-health", "event-vendors"],
    regions: ["global"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 10, max: 25 },
    parallelRunRecommended: false,
    pickerSubtitle: "Multi-vertical booking — client & booking export",
    livIntro: "SimplyBook exports clients and bookings from Reports. Paste both and Liv handles the rest.",
    entities: [
      csv("clients", ["SimplyBook → Reports → Clients → Export CSV."]),
      csv("appointments", ["Reports → Bookings → date range → CSV."]),
      csv("services", ["Services list export or paste from admin panel."]),
      manual("staff", ["Providers export from SimplyBook staff section."]),
    ],
  },
  {
    id: "schedulista",
    displayName: "Schedulista",
    verticals: ["hair", "beauty", "wellness"],
    regions: ["US", "CA"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 10, max: 20 },
    parallelRunRecommended: false,
    pickerSubtitle: "Solo stylist — client CSV",
    livIntro: "Schedulista client exports are simple. Share your booking page for service menu mirroring.",
    entities: [
      csv("clients", ["Schedulista → Clients → Export."]),
      {
        kind: "services",
        available: true,
        method: "public_booking_page",
        ownerSteps: ["Share your Schedulista booking URL for menu mirroring."],
        livPath: "concierge",
      },
      csv("appointments", ["Calendar → export upcoming appointments CSV if available."]),
      manual("staff", ["Solo — you're the team."]),
    ],
  },
  {
    id: "pabau",
    displayName: "Pabau",
    verticals: ["medspa", "beauty"],
    regions: ["GB", "IE"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 40 },
    parallelRunRecommended: true,
    pickerSubtitle: "UK medspa — client & appointment export",
    livIntro: "Pabau exports clients and appointments from CRM reports. Parallel run helps if your front desk still checks Pabau during cutover.",
    entities: [
      csv("clients", ["Pabau → Clients → Export CSV."]),
      csv("appointments", ["Diary / Reports → upcoming appointments → CSV."]),
      manual("services", ["Treatment list from Pabau catalog — paste CSV."]),
      manual("staff", ["Practitioner list from Pabau team settings."]),
    ],
  },
  {
    id: "shortcuts",
    displayName: "Shortcuts (Salon IQ)",
    verticals: ["hair", "beauty"],
    regions: ["AU", "NZ"],
    tier: "tier3_adjacent",
    livStatus: "csv_plus_guide",
    selfServeMinutesEstimate: { min: 20, max: 40 },
    parallelRunRecommended: true,
    pickerSubtitle: "AU/NZ salon — client export",
    livIntro: "Shortcuts client exports from Reports map well to Livia. Service menu from your price list CSV or booking page.",
    entities: [
      csv("clients", ["Shortcuts → Reports → Client list → CSV."]),
      csv("appointments", ["Appointment diary export for forward bookings."]),
      manual("services", ["Price list export or paste service CSV."]),
      manual("staff", ["Stylist roster from Shortcuts staff module."]),
    ],
  },
];
