// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-explorations/Atelier.tsx": () => import("../components/mockups/brand-explorations/Atelier.tsx"),
  "./components/mockups/brand-explorations/Aurora.tsx": () => import("../components/mockups/brand-explorations/Aurora.tsx"),
  "./components/mockups/brand-explorations/Pulse.tsx": () => import("../components/mockups/brand-explorations/Pulse.tsx"),
  "./components/mockups/bliq-dashboards/Atrium.tsx": () => import("../components/mockups/bliq-dashboards/Atrium.tsx"),
  "./components/mockups/bliq-dashboards/Cockpit.tsx": () => import("../components/mockups/bliq-dashboards/Cockpit.tsx"),
  "./components/mockups/bliq-dashboards/Concierge.tsx": () => import("../components/mockups/bliq-dashboards/Concierge.tsx")
};
