// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/livia-dashboards/Cockpit.tsx": () => import("../components/mockups/livia-dashboards/Cockpit.tsx"),
  "./components/mockups/livia-wordmarks/Atelier.tsx": () => import("../components/mockups/livia-wordmarks/Atelier.tsx"),
  "./components/mockups/livia-wordmarks/Aurum.tsx": () => import("../components/mockups/livia-wordmarks/Aurum.tsx"),
  "./components/mockups/livia-wordmarks/Empress.tsx": () => import("../components/mockups/livia-wordmarks/Empress.tsx"),
  "./components/mockups/livia-wordmarks/Maison.tsx": () => import("../components/mockups/livia-wordmarks/Maison.tsx"),
  "./components/mockups/livia-wordmarks/Monogram.tsx": () => import("../components/mockups/livia-wordmarks/Monogram.tsx"),
  "./components/mockups/livia-wordmarks/SoftModern.tsx": () => import("../components/mockups/livia-wordmarks/SoftModern.tsx")
};
